### ISSUE TITLE
Cannot start ustvgo-iptv using the Autostart tutorial provided by the script creator.

### ISSUE THREAD

**Issue by Nostradamus1973** [interlark/ustvgo-tvguide#2] opened 2022-08-01 10:48 UTC
(I thought I posted this issue a few hours ago, apparently I didn't have enough coffee)
Good morning everyone,

I've been using this script for a few days now and I'm LOVING it. Unfortunately, there is a huge problem for me because I can't get ustvgp-iptv to start as a service with Kubuntu 22.04; I've looked at the tutorial and gone through it repeatedly only to fail to start every time. Having to manually restart this won't work for me, so, I'm wondering if anyone else is having problems pertaining to Autostarting in Ubuntu. I've gone through the Autostart instruction set over and over again(without any luck), if someone could please help me with this I'd be very grateful.

Thank you for your help and time.

**Comment by yarafie** [comment] 2022-08-01 11:12
Maybe you need to look into running this in a docker
BTW you did post it earlier but under ustvgo-iptv :)

**Comment by interlark** [comment] 2022-08-07 13:23
Closed as duplicate of https://github.com/interlark/ustvgo-iptv/issues/30

**Closed as completed by interlark** 2022-08-07 13:23 UTC
